nguyencongthang_231230913_de01/Models/ComputerDbContext.cs
using Microsoft.EntityFrameworkCore;
namespace nguyencongthang_231230913_de01.Models
{
    public class ComputerDbContext : DbContext
    {
        public ComputerDbContext(DbContextOptions<ComputerDbContext> options) : base(options) { }
        public DbSet<nctComputer> nctComputers { get; set; }
    }
}

nguyencongthang_231230913_de01/Models/ErrorViewModel.cs
namespace nguyencongthang_231230913_de01.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

nguyencongthang_231230913_de01/Models/nctComputer.cs
using System.ComponentModel.DataAnnotations;

namespace nguyencongthang_231230913_de01.Models
{
    public class nctComputer
    {
        [Key]
        public int? nctComId { get; set; }
        public string? nctComName { get; set; }
        public double? nctComPrice { get; set; }
        public string? nctComImage { get; set; }
        public bool? nctComStatus { get; set; }
    }
}

nguyencongthang_231230913_de01/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using nguyencongthang_231230913_de01.Models;

namespace nguyencongthang_231230913_de01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult nctIndex()
        {
            return View();
        }

        public IActionResult nctPrivacy()
        {
            return View();
        }

        public IActionResult nctContact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult nctError()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

nguyencongthang_231230913_de01/Controllers/nctComputersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using nguyencongthang_231230913_de01.Models;

namespace nguyencongthang_231230913_de01.Controllers
{
    public class nctComputersController : Controller
    {
        private readonly ComputerDbContext _context;

        public nctComputersController(ComputerDbContext context)
        {
            _context = context;
        }

        // GET: nctComputers
        public async Task<IActionResult> nctIndex()
        {
            return View(await _context.nctComputers.ToListAsync());
        }

        // GET: nctComputers/Details/5
        public async Task<IActionResult> nctDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nctComputer = await _context.nctComputers
                .FirstOrDefaultAsync(m => m.nctComId == id);
            if (nctComputer == null)
            {
                return NotFound();
            }

            return View(nctComputer);
        }

        // GET: nctComputers/Create
        public IActionResult nctCreate()
        {
            return View();
        }

        // POST: nctComputers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> nctCreate([Bind("nctComId,nctComName,nctComPrice,nctComImage,nctComStatus")] nctComputer nctComputer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nctComputer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(nctIndex));
            }
            return View(nctComputer);
        }

        // GET: nctComputers/Edit/5
        public async Task<IActionResult> nctEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nctComputer = await _context.nctComputers.FindAsync(id);
            if (nctComputer == null)
            {
                return NotFound();
            }
            return View(nctComputer);
        }

        // POST: nctComputers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> nctEdit(int? id, [Bind("nctComId,nctComName,nctComPrice,nctComImage,nctComStatus")] nctComputer nctComputer)
        {
            if (id != nctComputer.nctComId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nctComputer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!nctComputerExists(nctComputer.nctComId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(nctIndex));
            }
            return View(nctComputer);
        }

        // GET: nctComputers/Delete/5
        public async Task<IActionResult> nctDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nctComputer = await _context.nctComputers
                .FirstOrDefaultAsync(m => m.nctComId == id);
            if (nctComputer == null)
            {
                return NotFound();
            }

            return View(nctComputer);
        }

        // POST: nctComputers/Delete/5
        [HttpPost, ActionName("nctDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> nctDeleteConfirmed(int? id)
        {
            var nctComputer = await _context.nctComputers.FindAsync(id);
            if (nctComputer != null)
            {
                _context.nctComputers.Remove(nctComputer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(nctIndex));
        }

        private bool nctComputerExists(int? id)
        {
            return _context.nctComputers.Any(e => e.nctComId == id);
        }
    }
}

nguyencongthang_231230913_de01/Views/Home/nctContact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h1>@ViewData["Title"]</h1>

<table class="table">
    <tr class="d-lg-table-row">
        <td class="fw-bold">Họ và tên</td>
        <td>Nguyễn Công Thắng</td>
    </tr>
    <tr class="d-lg-table-row">
        <td class="fw-bold">MSSV</td>
        <td>231230913</td>
    </tr>
    <tr class="d-lg-table-row">
        <td class="fw-bold">Lớp</td>
        <td>CNTT1-K64</td>
    </tr>
    <tr class="d-lg-table-row">
        <td class="fw-bold">Email</td>
        <td>thang231230913@lms.utc.edu.vn</td>
    </tr>
    <tr class="d-lg-table-row">
        <td class="fw-bold">Số điện thoại</td>
        <td>0972857436</td>
    </tr>
</table>

nguyencongthang_231230913_de01/Views/Home/nctIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

nguyencongthang_231230913_de01/Views/Home/nctPrivacy.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

nguyencongthang_231230913_de01/Views/Shared/_nctLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - nguyencongthang_231230913_de01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/nguyencongthang_231230913_de01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="nctIndex">nguyencongthang_231230913_de01</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="nctIndex">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="nctPrivacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="nctComputers" asp-action="nctIndex">Computer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="nctContact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - nguyencongthang_231230913_de01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

nguyencongthang_231230913_de01/Views/nctComputers/nctCreate.cshtml
@model nguyencongthang_231230913_de01.Models.nctComputer

@{
    ViewData["Title"] = "nctCreate";
}

<h1>nctCreate</h1>

<h4>nctComputer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="nctCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nctComName" class="control-label"></label>
                <input asp-for="nctComName" class="form-control" />
                <span asp-validation-for="nctComName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nctComPrice" class="control-label"></label>
                <input asp-for="nctComPrice" class="form-control" />
                <span asp-validation-for="nctComPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nctComImage" class="control-label"></label>
                <input asp-for="nctComImage" class="form-control" />
                <span asp-validation-for="nctComImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nctComStatus" class="control-label"></label>
                <input asp-for="nctComStatus" class="form-control" />
                <span asp-validation-for="nctComStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="nctCreate" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="nctIndex">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

nguyencongthang_231230913_de01/Views/nctComputers/nctDelete.cshtml
@model nguyencongthang_231230913_de01.Models.nctComputer

@{
    ViewData["Title"] = "nctDelete";
}

<h1>nctDelete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>nctComputer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nctComName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nctComName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nctComPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nctComPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nctComImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nctComImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nctComStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nctComStatus)
        </dd>
    </dl>
    
    <form asp-action="nctDelete">
        <input type="hidden" asp-for="nctComId" />
        <input type="submit" value="nctDelete" class="btn btn-danger" /> |
        <a class="btn btn-primary" asp-action="nctIndex">Back to List</a>
    </form>
</div>

nguyencongthang_231230913_de01/Views/nctComputers/nctDetails.cshtml
@model nguyencongthang_231230913_de01.Models.nctComputer

@{
    ViewData["Title"] = "nctDetails";
}

<h1>nctDetails</h1>

<div>
    <h4>nctComputer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nctComName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nctComName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nctComPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nctComPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nctComImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nctComImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nctComStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nctComStatus)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-success" asp-action="nctEdit" asp-route-id="@Model?.nctComId">Edit</a> |
    <a class="btn btn-primary" asp-action="nctIndex">Back to List</a>
</div>

nguyencongthang_231230913_de01/Views/nctComputers/nctEdit.cshtml
@model nguyencongthang_231230913_de01.Models.nctComputer

@{
    ViewData["Title"] = "nctEdit";
}

<h1>nctEdit</h1>

<h4>nctComputer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="nctEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="nctComId" />
            <div class="form-group">
                <label asp-for="nctComName" class="control-label"></label>
                <input asp-for="nctComName" class="form-control" />
                <span asp-validation-for="nctComName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nctComPrice" class="control-label"></label>
                <input asp-for="nctComPrice" class="form-control" />
                <span asp-validation-for="nctComPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nctComImage" class="control-label"></label>
                <input asp-for="nctComImage" class="form-control" />
                <span asp-validation-for="nctComImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nctComStatus" class="control-label"></label>
                <input asp-for="nctComStatus" class="form-control" />
                <span asp-validation-for="nctComStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="nctIndex">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

nguyencongthang_231230913_de01/Views/nctComputers/nctIndex.cshtml
@model IEnumerable<nguyencongthang_231230913_de01.Models.nctComputer>

@{
    ViewData["Title"] = "nctIndex";
}

<h1>Index</h1>

<p>
    <a class="btn btn-primary" asp-action="nctCreate">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nctComName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nctComPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nctComImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nctComStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nctComName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nctComPrice)
            </td>
            <td>
                
                <img width="200px" src="@item.nctComImage" alt="Alternate Text" />
            </td>
            <td>
                @if (item.nctComStatus == true)
                {
                    <span class="badge bg-success">Còn hàng</span>
                }
                else
                {
                    <span class="badge bg-danger">Hết hàng</span>
                }
            </td>
            <td>
                <a class="btn btn-primary" asp-action="nctEdit" asp-route-id="@item.nctComId">Edit</a> |
                <a class="btn btn-secondary" asp-action="nctDetails" asp-route-id="@item.nctComId">Details</a> |
                <a class="btn btn-danger" asp-action="nctDelete" asp-route-id="@item.nctComId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>